version: '3.8'

services:
  xp-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - xp-network

  # Para testes de interoperabilidade
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - xp-app
    networks:
      - xp-network

  # Banco de dados para produção (opcional)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: xpdb
      POSTGRES_USER: xpuser
      POSTGRES_PASSWORD: xppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xp-network

networks:
  xp-network:
    driver: bridge

volumes:
  postgres_data:
