version: '3.8'

services:
  # Aplicação XP para testes DAST
  xp-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - dast-network

  # OWASP ZAP para testes de segurança
  zap:
    image: zaproxy/zap-stable
    ports:
      - "8081:8080"
    volumes:
      - ./zap-reports:/zap/wrk
    environment:
      - ZAP_PORT=8080
    networks:
      - dast-network
    depends_on:
      xp-app:
        condition: service_healthy
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true

networks:
  dast-network:
    driver: bridge

volumes:
  zap-reports:
